### ISSUE TITLE
Can't post a PriceList product for the life of me

### ISSUE THREAD

**Issue by susaree** [darroncockram/sdatasamples#1]
Using Sage50 and I've been stuck on trying to post a new entry onto a customer's pricelist for days, I will appreciate any help, thank you.

This is the response I get when I POST:
<?xml version="1.0" encoding="utf-8"?>
<diagnosis xmlns="http://schemas.sage.com/sdata/2008/1" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:opensearch="http://a9.com/-/spec/opensearch/1.1/" xmlns:sme="http://schemas.sage.com/sdata/sme/2007" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:sdata="http://schemas.sage.com/sdata/2008/1" xmlns:http="http://schemas.sage.com/sdata/http/2008/1" xmlns:sdatasync="http://schemas.sage.com/sdata/sync/2008/1">
    <sdata:severity>error</sdata:severity>
    <sdata:sdataCode>ApplicationDiagnosis</sdata:sdataCode>
    <sdata:applicationCode />
    <sdata:message>POST operation failed - Exception has been thrown by the target of an invocation.

   at System.RuntimeType.InvokeDispMethod(String name, BindingFlags invokeAttr, Object target, Object[] args, Boolean[] byrefModifiers, Int32 culture, String[] namedParameters)
   at System.RuntimeType.InvokeMember(String name, BindingFlags bindingFlags, Binder binder, Object target, Object[] providedArgs, ParameterModifier[] modifiers, CultureInfo culture, String[] namedParams)
   at Sage.Integration.Accounts50.SDOAdapter.SDORequestHandler.OnPostRecordRequest(SDOWorkspaceScope scope, ISDORecord record, FeedEntry feedEntry)
   at Sage.Integration.Accounts50.SDOAdapter.SDORequestHandler.OnPostRequest(IRequest request, FeedEntry feedEntry)
   at Sage.Integration.Accounts50.SDOAdapter.RequestHandler`2.OnPostRequest(IRequest request)
   at Sage.Integration.Accounts50.SDOAdapter.RequestHandler`2.PostRequest(IRequest request)
   at Sage.Integration.Accounts50.SDOAdapter.SDORequestManager.PostRequest(IRequest request) (-1)</sdata:message>
    <sdata:stackTrace />
    <sdata:payloadPath />
</diagnosis>

This is the request

POST XML:
<sdata:payload>
    <crm:price sdata:uuid="ba9bd275-e3ad-4372-b121-6f0e460d137d">
        <crm:active>true</crm:active>
        <crm:reference>1</crm:reference>
        <crm:status>confirmed</crm:status>
        <crm:customerSupplierFlag>Customer</crm:customerSupplierFlag>
        <crm:tradingAccount sdata:uuid="5580677e-cc30-46cb-84be-e16a463316a0"/>
         <crm:commodity sdata:uuid="3b01af63-3caa-4408-b843-f22841e60609" />
         <crm:pricelist sdata:uuid="7cb44807-de7d-42cb-a789-b7de2ebb7884" />
        <crm:unitOfMeasure xsi:nil="true" />
        <crm:location xsi:nil="true" />
        <crm:postalAddress xsi:nil="true" />
        <crm:currency>GBP</crm:currency>
        <crm:operatingCompanyCurrency>GBP</crm:operatingCompanyCurrency>
        <crm:operatingCompanyCurrencyExchangeRate>1.00</crm:operatingCompanyCurrencyExchangeRate>
        <crm:operatingCompanyCurrencyExchangeRateOperator>*</crm:operatingCompanyCurrencyExchangeRateOperator>
        <crm:operatingCompanyCurrencyExchangeRateDate xsi:nil="true" />
        <crm:decimalPlaces>2</crm:decimalPlaces>
        <crm:price>59.16</crm:price>
        <crm:includesTax>false</crm:includesTax>
        <crm:startDate xsi:nil="true" />
        <crm:endDate xsi:nil="true" />
        <crm:notes xsi:nil="true" />
    </crm:price>
</sdata:payload>

**Comment by darroncockram** [comment]
The prices endpoint is read only I'm afraid. If you check the schema you can see that sme:CanPost and sme:CanPut are both set to false for that feed.
